services:
  - type: web
    name: Bankruptcy-prediction-app
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PORT
        value: 5000